baseURL = "https://thomasdstewart.github.io/ryantrak/"
languageCode = "en-us"
title = "Ryanair Price Tracker"
theme = "simple"

[params]
  chartsTitle = "Flight Price Charts"
  chartsSubtitle = "Track how Ryanair prices change over time."
